name: null
favicon: null
layout_spectrum: 0.51669
typography_spectrum: 0.31113
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#409e52'
    - '#223e99'
    - '#000000'
    - '#00ff00'
    - '#0000ff'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
